### ISSUE TITLE
MC_NAME Environment Variable Not Used Correctly in WebSocket Server

### ISSUE THREAD

**Issue by KeSaite** [joanroig/admincraft#51]
# Bug Report

## Describe the Bug

The WebSocket server (`server.js`) is not correctly using the `MC_NAME` environment variable, even though it is passed correctly in the `docker-compose.yml` configuration. Instead, the script defaults to `minecraft`, causing Docker commands like `docker exec minecraft` to fail with the error `No such container: minecraft`.

---

## To Reproduce

1. Use the following `docker-compose.yml` configuration:

    ```yaml
    version: "3.8"
    services:
      admincraft-websocket:
        image: joanroig/admincraft-websocket:latest
        container_name: admincraft-websocket
        logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "3"
        restart: always
        networks:
          - 1panel-network
        ports:
          - "38092:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/admincraft/certs:/usr/src/app/certs:ro
        environment:
          SECRET_KEY: "your-secret-key"  # Replace with your secret key
          USE_SSL: "true"
          MC_NAME: "minecraft-bedrock-server"

    networks:
      1panel-network:
        external: true
    ```

2. Ensure the `minecraft-bedrock-server` container is running.

3. Connect to the WebSocket server and send a command (e.g., `list`).

4. Check the WebSocket server logs:
    ```bash
    docker logs admincraft-websocket
    ```
    **Observed error**:
    ```
    Execution error: Command failed: docker exec minecraft send-command list
    Error: No such container: minecraft
    ```

---

## Expected Behavior

The WebSocket server should correctly use the `MC_NAME` environment variable (`minecraft-bedrock-server`) to execute commands.

---

## Setup

- **OS**: Ubuntu 22.04
- **Docker version**: 27.5.0
- **Compose version**: 2.32.4
- **Node.js version**: 22.9.0
- **App version**: 1.0.0

---

## Possible Cause

1. **Improper use of template strings in `server.js`**:
    In some parts of the script, `${MC_NAME}` is enclosed in double quotes (`""`) instead of template literals (`` ``). For example:
    ```javascript
    executeCommand("docker restart ${MC_NAME}");
    ```
    This treats `${MC_NAME}` as a literal string instead of a variable.

2. **Lack of runtime validation for `MC_NAME`**:
    The script does not validate or log the value of `MC_NAME` at runtime, making it difficult to debug.

---

## Proposed Fix

1. Use template literals for all commands involving `MC_NAME`:
    ```javascript
    executeCommand(`docker exec ${MC_NAME} send-command ${msgString}`);
    ```

2. Add runtime debugging logs:
    ```javascript
    console.log("DEBUG: MC_NAME =", MC_NAME);
    console.log(`Executing command: docker exec ${MC_NAME} send-command ${msgString}`);
    ```

3. Add error handling to ensure `MC_NAME` is correctly set:
    ```javascript
    if (!MC_NAME) {
      console.error("Error: MC_NAME is not defined.");
      process.exit(1);
    }
    ```

---

## Additional Context

The `MC_NAME` variable works correctly when tested inside the container:
```bash
docker exec -it admincraft-websocket sh -c 'echo $MC_NAME'
```

Output:
```
minecraft-bedrock-server
```
However, it is not properly used in the WebSocket script, leading to command execution errors.

---

End of Issue
